//
export const UPDATE_EDITOR_STATUS="UPDATE_EDITOR_STATUS"
//更新场景选中配置文件
export const UPDATE_SCENE_SELECTED="UPDATE_SCENE_SELECTED"

//右侧组件切换
export const UPDATE_RIGHTSIDERTYPE = 'UPDATE_RIGHTSIDERTYPE'
 //显示loading
 export const UPDATE_SHOWLOADING= "UPDATE_SHOWLOADING"
 //更新当前设计信息
 export const UPDATE_CURRENT_DESIGN = "UPDATE_CURRENT_DESIGN"
 //更新编辑器模式
 export const UPDATE_EDITOR_MODE = "UPDATE_EDITOR_MODE"
 //更新当前模板信息
 export const UPDATE_CURRENT_TEMPLATE = "UPDATE_CURRENT_TEMPLATE"
 //更新当前预设信息
 export const UPDATE_CURRENT_PRESET = "UPDATE_CURRENT_PRESET"
 //更新未保存状态
 export const UPDATE_HAS_UNSAVED_CHANGES = "UPDATE_HAS_UNSAVED_CHANGES"
 //更新当前活动视图
 export const UPDATE_ACTIVE_VIEW = "UPDATE_ACTIVE_VIEW"
 //更新用户订阅信息
 export const UPDATE_USER_SUBSCRIPTION = "UPDATE_USER_SUBSCRIPTION"